baseurl = "http://iolara.white-knight.org/"
title = "Iolara Campaign Content"
author = "Mike Simpson"
languageCode = "en-us"

[params]
  logo      = "/images/logo.jpg"
  copyright = '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">Iolara campaign content</span> by <a xmlns:cc="http://creativecommons.org/ns#" href="mailto:stendhal9@white-knight.org" property="cc:attributionName" rel="cc:attributionURL">Mike Simpson</a> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.<br />Based on a work at <a xmlns:dct="http://purl.org/dc/terms/" href="http://iolara.white-knight.org/" rel="dct:source">https://iolara.white-knight.org/</a>.'
  twitter   = "https://twitter.com/stendhal9"
  facebook  = "https://www.facebook.com/stendhal9"
  github    = "https://github.com/stendhal9"
  email     = "stendhal9@white-knight.org"
  #analytics = "UA-12345678-9"

